name: Setup Crowdout credentials
description: Setup credentials to be able to run the Crowdout actions

inputs:
  export-env:
    description: "Export loaded secrets as environment variables"
    required: false
    default: false
  service-account-token:
    description: "1Password service account token"
    required: true
outputs:
  CMS_API_TOKEN:
    description: "Api token for Github - CMS communication"
    value: ${{ steps.load-crowdout-credentials.outputs.CMS_API_TOKEN }}
  CMS_PATH:
    description: "CMS url path"
    value: ${{ steps.load-crowdout-credentials.outputs.CMS_PATH }}
  CROWDOUT_SLACK_TOKEN:
    description: "Slack bot token"
    value: ${{ steps.load-crowdout-credentials.outputs.CROWDOUT_SLACK_TOKEN }}
  SLACK_USER_MAP_JSON:
    description: "Map of GitHub usernames to Slack user IDs in JSON format"
    value: ${{ steps.load-crowdout-credentials.outputs.SLACK_USER_MAP_JSON }}
  TRANSLATIONS_SLACK_CHANNEL_ID:
    description: "ID of the Translations Slack channel"
    value: ${{ steps.load-crowdout-credentials.outputs.TRANSLATIONS_SLACK_CHANNEL_ID }}



# Please be aware that importing this action will potentially
# export the following environment variables to the workflow:
#   - OP_SERVICE_ACCOUNT_TOKEN
#   - CMS_API_TOKEN
#   - CMS_PATH
#   - CROWDOUT_SLACK_TOKEN
#   - SLACK_USER_MAP_JSON
#   - TRANSLATIONS_SLACK_CHANNEL_ID
#
runs:
  using: composite
  steps:
    - name: Load Crowdout credentials
      id: load-crowdout-credentials
      uses: 1password/load-secrets-action@v2
      with:
        # Export loaded secrets as environment variables
        export-env: ${{ inputs.export-env }}
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ inputs.service-account-token }}
        CMS_API_TOKEN: op://github-cicd/CMS_API_TOKEN/credential
        CMS_PATH: op://github-cicd/CMS_PATH/url
        CROWDOUT_SLACK_TOKEN: op://github-cicd/CROWDOUT_SLACK_TOKEN/credential
        SLACK_USER_MAP_JSON: op://github-cicd/SLACK_USER_MAP_JSON/json
        TRANSLATIONS_SLACK_CHANNEL_ID: op://github-cicd/TRANSLATIONS_SLACK_CHANNEL_ID/id
