import Head from "next/head";
import Image from "next/image";
import {Inter} from "next/font/google";
import {serverSideTranslations} from 'next-i18next/serverSideTranslations'
import {GetStaticProps} from "next";
import {useTranslation} from "next-i18next";
import LanguageSwitcher from "@/components/language-switcher";
import {styles} from './index.styles'
import * as strings from '../public/locales/en/common.json'

const inter = Inter({subsets: ["latin"]});

const Home = () => {

    const translationKeys = Object.keys(strings)
    const {t} = useTranslation()
    return (
        <>
            <Head>
                <title>Test app</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main style={styles.wrapper} className={`${inter.className}`}>
                <LanguageSwitcher/>
                {translationKeys.filter(key => key !== 'default').map(key => <div key={key}><h3
                    style={{color: 'red'}}>{key}</h3>
                    <h3>{t(key)}</h3>
                </div>)}
            </main>
        </>
    );
}

export const getStaticProps: GetStaticProps = async ({locale}) => {
    return {
        props: {...(await serverSideTranslations(locale as string, ['common']))}
    }
}

export default Home
