name: Crowdin fetch translation into PR on trigger

on:
  pull_request:
    types: [opened]
    paths:
      - 'public/locales/en/**'

  issue_comment:
    types: [created]

jobs:
  crowdin-fetch-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: trigger
        with:
          trigger: '@fetch/crowdin'
          reaction: '+1'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - uses: actions/checkout@v3
        if: steps.trigger.outputs.triggered == 'true'

      - name: Checkout Pull Request
        if: ${{ github.event_name == 'issue_comment' && steps.trigger.outputs.triggered == 'true'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.issue.number }}
          echo "ISSUE_BRANCH=$(git branch --show-current)" >> $GITHUB_ENV

      - name: Install crowdin
        if: steps.trigger.outputs.triggered == 'true'
        run: |
          cd scripts/crowdin && npm i

      - name: Run crowdin pull and commit
        if: steps.trigger.outputs.triggered == 'true'
        env:
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
          CROWDIN_BRANCH: ${{ github.head_ref || env.ISSUE_BRANCH }}
          CROWDIN_OPERATION: "Pull and commit translations"
        run: |
          node ./scripts/crowdin/crowdin-operations.mjs

      - name: Comment PR
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            There was an issue fetching your translations from crowdin! :confused:
            Please check the action output in
            https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}
